### ISSUE TITLE
kv2 create_or_update_secret response.json() failse

### ISSUE THREAD

**Issue by TerryHowe** [hvac/hvac#385]
https://github.com/hvac/hvac/blob/develop/hvac/api/secrets_engines/kv_v2.py#L124

Blows up because the server returns and empty body and 204s me.  It would be nice if a response wasn't required on update.

**Comment by jeffwecan** [comment]
So you're seeing exceptions thrown upon a 204 response during updates in particular? I've run into the same issue on occasion and I want to say it only manifests with certain versions of Vault... In any case, I'll be sure to take a look and add any appropriate regression test cases before we cut the next hvac release. 👍

**Comment by TerryHowe** [comment]
I'm using basic docker vault btw
```{
    "backend": {
        "file": {
            "path": "/vault/file"
        }
    },
    "listener": {
        "tcp": {
            "address": "0.0.0.0:${PORT}",
            "tls_disable": 1
        }
    },
    "default_lease_ttl": "168h",
    "max_lease_ttl": "720h",
    "disable_mlock": true
}
```

**Comment by ba1dr** [comment]
I have the same issue with vault (`1.1.3`) installed from Docker.

The code below executes and **value is set**. Reading returns correct value.

    client.secrets.kv.v2.create_or_update_secret(
        path='kv/test2', mount_point='kv/',
        secret={'value': 18})

Output from `requests` (I've added `print` before json parsing):
```
code: 204
headers: {'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Tue, 30 Jul 2019 14:53:16 GMT'}
text: ""
```

`hvac==0.9.5`.

`docker-compose.yml`:
```
version: '2'
services:
    myvault:
        image: vault
        container_name: myvault
        ports:
          - "8200:8200"
        volumes:
          - /usr/local/lib/vault/data:/vault/data:rw
          - /usr/local/etc/vault:/vault/config:rw
        cap_add:
          - IPC_LOCK
        command: vault server -config=/vault/config/config.json

```

`config.json`:
```
{
  "listener":  {
    "tcp":  {
      "address":  "0.0.0.0:8200",
      "tls_disable":  "true"
    }
  },
  "storage" :{
        "file" : {
            "path" : "/vault/data"
        }
  },
  "default_lease_ttl": "168h",
  "max_lease_ttl": "0h",
  "api_addr": "http://0.0.0.0:8200"
}
```
