### ISSUE TITLE
Relax requests requirement version

### ISSUE THREAD

**Issue by intgr** [hvac/hvac#893]
hvac 1.0.0 currently has a strict version requirement on `requests`:

```toml
[tool.poetry.dependencies]
# ...
requests = "2.27.1"
```

But when my project is already using the latest `requests` version 2.28.1, this conflicts with hvac.

Libraries like hvac should not add such strict requirements to their runtime dependencies, especially for so widely used libraries like requests.
